# Generated by Django 5.0.6 on 2024-05-20 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.CharField(max_length=150)),
                ('description_recipe', models.TextField()),
                ('cooking_steps', models.TextField()),
                ('cooking_time', models.TimeField()),
                ('image_recipe', models.ImageField(upload_to='recipes/')),
                ('author_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipes_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.category')),
            ],
        ),
    ]
